import java.util.Scanner;
import java.util.Random;


public class JavaGuessingGame
{

	public static void main( String[ ] args )
			{
				Random rand = new Random ( ); // Get random number generator
				int compNumber = rand.nextInt ( 11 ) + 10; // Declare var int number and give it value of the next random range of
																			// 10 and 20.
				Scanner scanner = new Scanner ( System.in ); // create new scanner for system.in (user input)
				
				System.out.println( 
		            "A number is chosen "
		            + "between 10 to 20. "
		            + "Guess the number "
		            + "within 5 trials. "
		            + "you'll be given 5 chances to guess correctly ");
				
				System.out.println ( "what is your number? " );

				int userNumber = scanner.nextInt ( ); // declare int inputNumber, assign it user input

				System.out.println ( compNumber + " compNumber" ); // system output random # generated by computer

				System.out.println ( userNumber + " userNumber"); // system output userNumber inputed at line 18
				int score = 0; //initialize score variable
				
				
				
				
				
				
				
				while( userNumber != compNumber) {
					userNumber = scanner.nextInt();
			}
				
				for (int i = 5; i >= 0; i-- )
				{	
						//System.out.println("Guess the number");
					if ( compNumber > userNumber  ) // create if statment with parameter of "compNumber > userNumber"
					{
						System.out.println ( "Too low" );
						System.out.println ( i + " Tries remaining");
						//i--; // subtrace one from index 
						
					
						
					} // alert user they guessed too low

					else if ( userNumber > compNumber)
					{
						System.out.println ( "too high" );
						System.out.println ( i + " Tries remaining");
						
						
					}
					else 
					{
							System.out.println ("Correct" );
							score = score + i; 
							System.out.println ( "Your score is " + score ); // alert user of their
							
					}
					
					
					System.out.println("Guess the number");
					userNumber = scanner.nextInt ( ); // declare int inputNumber, assign it user input

					System.out.println ( compNumber ); // system output random # generated by computer
					System.out.println ( userNumber ); // system output userNumber inputed at line 18
					
					
					
					
					
					
					
					
					//finalScore = finalScore + score;
					


					// Tyler Wallace 10/1/2020
					/* issue with inverting the index so that it subtracts as opposed to adding to I, 
						testing the future assignment too for keeping total score as shown in commented out code.
						having additonal issues with allowing user to continue playing indefinitely until past 5 tries. 
					 	*/

				}
			}
}
// Part 4:
// Every time they guess they will get one point less starting with 5 points.
// For example, if they guess the number on the second time they will get 4 points instead of 5.
// If they take 4 turns to guess the correct number they will only get 2 points. T
// he player cannot go into negative numbers for points.
// Even if they are out of points they will have to continue to guess.
// Output the score. Hints: When testing your program output the random number so you can test if the points are adding
// up correctly.
