import java.util.Scanner;
import java.util.Random;

public class randomNumGeneratorHW
{

	public static void main( String[ ] args )
	{
	Scanner scanner = new Scanner(System.in);
		
		//Random rand = new Random ( ); // Get random number generator
		//int compNumber = rand.nextInt ( 11 ) + 10;
		
	
		System.out.println( 
            "A number is chosen "
            + " between 10 to 20. "
            + "Guess the number "
            + " within 5 trials. "
            + " youll be given 5 chances to guess correctly "
            + "Your score will be added based unpon how many guessess you have remaining.");
		
		Random rand = new Random ( ); // Get random number generator
		int compNumber = rand.nextInt ( 11 ) + 10;
		
		System.out.println ( "what is your number?");
		int userNumber = scanner.nextInt();
		
		System.out.println ( compNumber ); // system output random # generated by computer

		System.out.println ( userNumber ); // system output userNumber inputed at line 18
		
		int k = 0;// total number of guesses
		int i = 5;// total numbner of attempts
		int score = 0;
		int finalScore = 0;//initialize score variable
		
		//finalScore = finalScore + score;
			
		for ( i = 5; i >= k; i--)
		{	
				//System.out.println("Guess the number");
			if ( compNumber > userNumber  ) // create if statment with parameter of "compNumber > userNumber"
			{
				System.out.println ( "Too low" );
				break;
				
			} // alert user they guessed too low

			else if ( userNumber > compNumber)
			{
				System.out.println ( "too high" );
				System.out.println ( i + " Tries remaining");
			
			}
			else 
			{
					System.out.println ("Correct" ); 
					System.out.println ( "Your score is " + score + i ); // alert user of their
					break;
			}
		}
			
			System.out.println ( i + " Tries remaining"); // show user how many guesses remain of their 5 
			
			System.out.println("Guess the number");
			userNumber = scanner.nextInt ( ); // declare int inputNumber, assign it user input

			System.out.println ( compNumber ); // system output random # generated by computer
			System.out.println ( userNumber );// system output userNumber inputed at line 18
			
			finalScore = 0;
			finalScore = finalScore + i;
			System.out.println ( "Your total score is " + finalScore );
			
			System.out.println("Guess the number");
			userNumber = scanner.nextInt(-i ); // declare int inputNumber, assign it user input

			
			System.out.println (finalScore = finalScore + score  );

		// Tyler Wallace 09/26/2020
		
		 // issue with inverting the index so that it subtracts as opposed to adding to I, testing the future assignment
		 //too for keeping total score as shown in commented out code. having additonal issues with allowing user to
		 // continue playing indefinitely until past 5 tries.
		
		
		
/*Random rand = new Random( );
int secretNumb = rand.nextInt(11)+10;
boolean correct = false;

Scanner scanner = new Scanner(System.in);

System.out.println("give me a secret number");
int guess = scanner.nextInt();

System.out.println ( "give me a number" );

while (!correct)
{System.out.println ( "give me a number" );
guess = scanner.nextInt();

if (guess == secretNumb)
{
	correct = true;
}
System.out.println ( "You're right" );
}
if (guess  < secretNumb) 
{
	System.out.println("Higher");
}
else if (guess > secretNumb)
{
		System.out.println("lower");
}*/




}
	
}

